apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: $FUNCTION_NAME
  labels:
    cloud.googleapis.com/location: $REGION
  annotations:
    # run.googleapis.com/ingress: internal-and-cloud-load-balancing
    # run.googleapis.com/ingress-status: internal-and-cloud-load-balancing
    # run.googleapis.com/vpc-access-egress: private-ranges-only
    run.googleapis.com/vpc-access-connector: projects/fao-maps-review/locations/us-central1/connectors/fao-maps-vpc-connector
spec:
  template:
    metadata:
      labels:
        app: $NAME
        run.googleapis.com/startupProbeType: Default
      annotations:
        autoscaling.knative.dev/maxScale: '1'
        autoscaling.knative.dev/minScale: '1'
        # run.googleapis.com/ingress: all
        # run.googleapis.com/ingress-status: all
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/sessionAffinity: 'true'

    spec:
      serviceAccountName: $SERVICE_ACCOUNT_NAME
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: $TAG
          env:
            # - name: ES_API_KEY check ./Dockerfile
            #   value: $_ES_API_KEY
            - name: BACKEND
              value: $BACKEND
            - name: ENVIRONMENT
              value: $ENVIRONMENT
            - name: APP_PORT
              value: $APP_PORT
            - name: APP_HOST
              value: $APP_HOST
            - name: RELOAD
              value: $RELOAD
          ports:
            #- name: h2c
            - name: http1
              containerPort: 80
          resources:
            limits:
              cpu: 1000m
              memory: 4Gi


  traffic:
    - percent: 100
      latestRevision: true
