apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: $NAME
  labels:
    cloud.googleapis.com/location: $REGION
  annotations:
spec:
  template:
    metadata:
      labels:
        app: $NAME
        run.googleapis.com/startupProbeType: Default
      annotations:
        run.googleapis.com/cloudsql-instances: $PROJECT_ID:$REGION:$DB_INSTANCE_ID
        autoscaling.knative.dev/maxScale: '1'
        autoscaling.knative.dev/minScale: '1'
        # run.googleapis.com/ingress: all
        # run.googleapis.com/ingress-status: all
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/sessionAffinity: 'true'

    spec:
      serviceAccountName: $SERVICE_ACCOUNT_NAME
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: $TAG
          env:
            - name: APP_SETTINGS
              value: $APP_SETTINGS
            - name: DATABASE_URL
              value: $DATABASE_URL
            - name: APP_PORT
              value: $APP_PORT
            - name: USER_REGISTRY_BASE_URL
              value: $USER_REGISTRY_BASE_URL
            - name: SECRET_KEY
              value: $SECRET_KEY
          ports:
            #- name: h2c
            - name: http1
              containerPort: $APP_PORT
          resources:
            limits:
              cpu: 1000m
              memory: 4Gi
  traffic:
    - percent: 100
      latestRevision: true
